<a href="https://colab.research.google.com/github/Subho-Halder/Hands_on_python/blob/main/Pokemon_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
df=pd.read_csv('/content/pokemon_data.csv')

#print(df.head())

In [7]:
#print all columns
print(df.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [9]:
#print column [Name] upto 5 rows
print(df['Name'][0:5])

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [11]:
#print multiple columns
print(df[['Name','Type 1','Type 2']])

                      Name   Type 1  Type 2
0                Bulbasaur    Grass  Poison
1                  Ivysaur    Grass  Poison
2                 Venusaur    Grass  Poison
3    VenusaurMega Venusaur    Grass  Poison
4               Charmander     Fire     NaN
..                     ...      ...     ...
795                Diancie     Rock   Fairy
796    DiancieMega Diancie     Rock   Fairy
797    HoopaHoopa Confined  Psychic   Ghost
798     HoopaHoopa Unbound  Psychic    Dark
799              Volcanion     Fire   Water

[800 rows x 3 columns]

In [12]:
# print specific row
print(df.iloc[1])

#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

In [16]:
# print multiple  row
print(df.iloc[0:4])

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False

In [22]:
#print specific element(R,C)
print(df.iloc[2,1])

Venusaur

In [28]:
#loc function to access filter
print(df.loc[df['Type 1']=='Fire'])

       #                       Name Type 1    Type 2   HP  Attack  Defense  \
4      4                 Charmander   Fire       NaN   39      52       43
5      5                 Charmeleon   Fire       NaN   58      64       58
6      6                  Charizard   Fire    Flying   78      84       78
7      6  CharizardMega Charizard X   Fire    Dragon   78     130      111
8      6  CharizardMega Charizard Y   Fire    Flying   78     104       78
42    37                     Vulpix   Fire       NaN   38      41       40
43    38                  Ninetales   Fire       NaN   73      76       75
63    58                  Growlithe   Fire       NaN   55      70       45
64    59                   Arcanine   Fire       NaN   90     110       80
83    77                     Ponyta   Fire       NaN   50      85       55
84    78                   Rapidash   Fire       NaN   65     100       70
135  126                     Magmar   Fire       NaN   65      95       57
147  136                    Flareon   Fire       NaN   65     130       60
158  146                    Moltres   Fire    Flying   90     100       90
169  155                  Cyndaquil   Fire       NaN   39      52       43
170  156                    Quilava   Fire       NaN   58      64       58
171  157                 Typhlosion   Fire       NaN   78      84       78
236  218                     Slugma   Fire       NaN   40      40       40
237  219                   Magcargo   Fire      Rock   50      50      120
259  240                      Magby   Fire       NaN   45      75       37
263  244                      Entei   Fire       NaN  115     115       85
270  250                      Ho-oh   Fire    Flying  106     130       90
276  255                    Torchic   Fire       NaN   45      60       40
277  256                  Combusken   Fire  Fighting   60      85       60
278  257                   Blaziken   Fire  Fighting   80     120       70
279  257      BlazikenMega Blaziken   Fire  Fighting   80     160       80
352  322                      Numel   Fire    Ground   60      60       40
353  323                   Camerupt   Fire    Ground   70     100       70
354  323      CameruptMega Camerupt   Fire    Ground   70     120      100
355  324                    Torkoal   Fire       NaN   70      85      140
435  390                   Chimchar   Fire       NaN   44      58       44
436  391                   Monferno   Fire  Fighting   64      78       52
437  392                  Infernape   Fire  Fighting   76     104       71
518  467                  Magmortar   Fire       NaN   75      95       67
542  485                    Heatran   Fire     Steel   91      90      106
557  498                      Tepig   Fire       NaN   65      63       45
558  499                    Pignite   Fire  Fighting   90      93       55
559  500                     Emboar   Fire  Fighting  110     123       65
572  513                    Pansear   Fire       NaN   50      53       48
573  514                   Simisear   Fire       NaN   75      98       63
614  554                   Darumaka   Fire       NaN   70      90       45
615  555    DarmanitanStandard Mode   Fire       NaN  105     140       55
616  555         DarmanitanZen Mode   Fire   Psychic  105      30      105
692  631                    Heatmor   Fire       NaN   85      97       66
721  653                   Fennekin   Fire       NaN   40      45       40
722  654                    Braixen   Fire       NaN   59      59       58
723  655                    Delphox   Fire   Psychic   75      69       72
730  662                Fletchinder   Fire    Flying   62      73       55
731  663                 Talonflame   Fire    Flying   78      81       71
735  667                     Litleo   Fire    Normal   62      50       58
736  668                     Pyroar   Fire    Normal   86      68       72
799  721                  Volcanion   Fire     Water   80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
4         60       50     65           1      False
5         80       65     80           1      False
6        109       85    100           1      False
7        130       85    100           1      False
8        159      115    100           1      False
42        50       65     65           1      False
43        81      100    100           1      False
63        70       50     60           1      False
64       100       80     95           1      False
83        65       65     90           1      False
84        80       80    105           1      False
135      100       85     93           1      False
147       95      110     65           1      False
158      125       85     90           1       True
169       60       50     65           2      False
170       80       65     80           2      False
171      109       85    100           2      False
236       70       40     20           2      False
237       80       80     30           2      False
259       70       55     83           2      False
263       90       75    100           2       True
270      110      154     90           2       True
276       70       50     45           3      False
277       85       60     55           3      False
278      110       70     80           3      False
279      130       80    100           3      False
352       65       45     35           3      False
353      105       75     40           3      False
354      145      105     20           3      False
355       85       70     20           3      False
435       58       44     61           4      False
436       78       52     81           4      False
437      104       71    108           4      False
518      125       95     83           4      False
542      130      106     77           4       True
557       45       45     45           5      False
558       70       55     55           5      False
559      100       65     65           5      False
572       53       48     64           5      False
573       98       63    101           5      False
614       15       45     50           5      False
615       30       55     95           5      False
616      140      105     55           5      False
692      105       66     65           5      False
721       62       60     60           6      False
722       90       70     73           6      False
723      114      100    104           6      False
730       56       52     84           6      False
731       74       69    126           6      False
735       73       54     72           6      False
736      109       66    106           6      False
799      130       90     70           6       True

In [26]:
#itering through data
for index, row in df.iterrows():
  print(index, row['Name'])

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoran (Female)
35 Nidorina
36 Nidoqueen
37 Nidoran (Male)
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 Victreebel
78 Tentacool
79 Tentacruel
80 Geodude
81 Graveler
82 Golem
83 Ponyta
84 Rapidash
85 Slowpoke
86 Slowbro
87 SlowbroMega Slowbro
88 Magnemite
89 Magneton
90 Farfetch'd
91 Doduo
92 Dodrio
93 Seel
94 Dewgong
95 Grimer
96 Muk
97 Shellder
98 Cloyster
99 Gastly
100 Haunter
101 Gengar
102 GengarMega Gengar
103 Onix
104 Drowzee
105 Hypno
106 Krabby
107 Kingler
108 Voltorb
109 Electrode
110 Exeggcute
111 Exeggutor
112 Cubone
113 Marowak
114 Hitmonlee
115 Hitmonchan
116 Lickitung
117 Koffing
118 Weezing
119 Rhyhorn
120 Rhydon
121 Chansey
122 Tangela
123 Kangaskhan
124 KangaskhanMega Kangaskhan
125 Horsea
126 Seadra
127 Goldeen
128 Seaking
129 Staryu
130 Starmie
131 Mr. Mime
132 Scyther
133 Jynx
134 Electabuzz
135 Magmar
136 Pinsir
137 PinsirMega Pinsir
138 Tauros
139 Magikarp
140 Gyarados
141 GyaradosMega Gyarados
142 Lapras
143 Ditto
144 Eevee
145 Vaporeon
146 Jolteon
147 Flareon
148 Porygon
149 Omanyte
150 Omastar
151 Kabuto
152 Kabutops
153 Aerodactyl
154 AerodactylMega Aerodactyl
155 Snorlax
156 Articuno
157 Zapdos
158 Moltres
159 Dratini
160 Dragonair
161 Dragonite
162 Mewtwo
163 MewtwoMega Mewtwo X
164 MewtwoMega Mewtwo Y
165 Mew
166 Chikorita
167 Bayleef
168 Meganium
169 Cyndaquil
170 Quilava
171 Typhlosion
172 Totodile
173 Croconaw
174 Feraligatr
175 Sentret
176 Furret
177 Hoothoot
178 Noctowl
179 Ledyba
180 Ledian
181 Spinarak
182 Ariados
183 Crobat
184 Chinchou
185 Lanturn
186 Pichu
187 Cleffa
188 Igglybuff
189 Togepi
190 Togetic
191 Natu
192 Xatu
193 Mareep
194 Flaaffy
195 Ampharos
196 AmpharosMega Ampharos
197 Bellossom
198 Marill
199 Azumarill
200 Sudowoodo
201 Politoed
202 Hoppip
203 Skiploom
204 Jumpluff
205 Aipom
206 Sunkern
207 Sunflora
208 Yanma
209 Wooper
210 Quagsire
211 Espeon
212 Umbreon
213 Murkrow
214 Slowking
215 Misdreavus
216 Unown
217 Wobbuffet
218 Girafarig
219 Pineco
220 Forretress
221 Dunsparce
222 Gligar
223 Steelix
224 SteelixMega Steelix
225 Snubbull
226 Granbull
227 Qwilfish
228 Scizor
229 ScizorMega Scizor
230 Shuckle
231 Heracross
232 HeracrossMega Heracross
233 Sneasel
234 Teddiursa
235 Ursaring
236 Slugma
237 Magcargo
238 Swinub
239 Piloswine
240 Corsola
241 Remoraid
242 Octillery
243 Delibird
244 Mantine
245 Skarmory
246 Houndour
247 Houndoom
248 HoundoomMega Houndoom
249 Kingdra
250 Phanpy
251 Donphan
252 Porygon2
253 Stantler
254 Smeargle
255 Tyrogue
256 Hitmontop
257 Smoochum
258 Elekid
259 Magby
260 Miltank
261 Blissey
262 Raikou
263 Entei
264 Suicune
265 Larvitar
266 Pupitar
267 Tyranitar
268 TyranitarMega Tyranitar
269 Lugia
270 Ho-oh
271 Celebi
272 Treecko
273 Grovyle
274 Sceptile
275 SceptileMega Sceptile
276 Torchic
277 Combusken
278 Blaziken
279 BlazikenMega Blaziken
280 Mudkip
281 Marshtomp
282 Swampert
283 SwampertMega Swampert
284 Poochyena
285 Mightyena
286 Zigzagoon
287 Linoone
288 Wurmple
289 Silcoon
290 Beautifly
291 Cascoon
292 Dustox
293 Lotad
294 Lombre
295 Ludicolo
296 Seedot
297 Nuzleaf
298 Shiftry
299 Taillow
300 Swellow
301 Wingull
302 Pelipper
303 Ralts
304 Kirlia
305 Gardevoir
306 GardevoirMega Gardevoir
307 Surskit
308 Masquerain
309 Shroomish
310 Breloom
311 Slakoth
312 Vigoroth
313 Slaking
314 Nincada
315 Ninjask
316 Shedinja
317 Whismur
318 Loudred
319 Exploud
320 Makuhita
321 Hariyama
322 Azurill
323 Nosepass
324 Skitty
325 Delcatty
326 Sableye
327 SableyeMega Sableye
328 Mawile
329 MawileMega Mawile
330 Aron
331 Lairon
332 Aggron
333 AggronMega Aggron
334 Meditite
335 Medicham
336 MedichamMega Medicham
337 Electrike
338 Manectric
339 ManectricMega Manectric
340 Plusle
341 Minun
342 Volbeat
343 Illumise
344 Roselia
345 Gulpin
346 Swalot
347 Carvanha
348 Sharpedo
349 SharpedoMega Sharpedo
350 Wailmer
351 Wailord
352 Numel
353 Camerupt
354 CameruptMega Camerupt
355 Torkoal
356 Spoink
357 Grumpig
358 Spinda
359 Trapinch
360 Vibrava
361 Flygon
362 Cacnea
363 Cacturne
364 Swablu
365 Altaria
366 AltariaMega Altaria
367 Zangoose
368 Seviper
369 Lunatone
370 Solrock
371 Barboach
372 Whiscash
373 Corphish
374 Crawdaunt
375 Baltoy
376 Claydol
377 Lileep
378 Cradily
379 Anorith
380 Armaldo
381 Feebas
382 Milotic
383 Castform
384 Kecleon
385 Shuppet
386 Banette
387 BanetteMega Banette
388 Duskull
389 Dusclops
390 Tropius
391 Chimecho
392 Absol
393 AbsolMega Absol
394 Wynaut
395 Snorunt
396 Glalie
397 GlalieMega Glalie
398 Spheal
399 Sealeo
400 Walrein
401 Clamperl
402 Huntail
403 Gorebyss
404 Relicanth
405 Luvdisc
406 Bagon
407 Shelgon
408 Salamence
409 SalamenceMega Salamence
410 Beldum
411 Metang
412 Metagross
413 MetagrossMega Metagross
414 Regirock
415 Regice
416 Registeel
417 Latias
418 LatiasMega Latias
419 Latios
420 LatiosMega Latios
421 Kyogre
422 KyogrePrimal Kyogre
423 Groudon
424 GroudonPrimal Groudon
425 Rayquaza
426 RayquazaMega Rayquaza
427 Jirachi
428 DeoxysNormal Forme
429 DeoxysAttack Forme
430 DeoxysDefense Forme
431 DeoxysSpeed Forme
432 Turtwig
433 Grotle
434 Torterra
435 Chimchar
436 Monferno
437 Infernape
438 Piplup
439 Prinplup
440 Empoleon
441 Starly
442 Staravia
443 Staraptor
444 Bidoof
445 Bibarel
446 Kricketot
447 Kricketune
448 Shinx
449 Luxio
450 Luxray
451 Budew
452 Roserade
453 Cranidos
454 Rampardos
455 Shieldon
456 Bastiodon
457 Burmy
458 WormadamPlant Cloak
459 WormadamSandy Cloak
460 WormadamTrash Cloak
461 Mothim
462 Combee
463 Vespiquen
464 Pachirisu
465 Buizel
466 Floatzel
467 Cherubi
468 Cherrim
469 Shellos
470 Gastrodon
471 Ambipom
472 Drifloon
473 Drifblim
474 Buneary
475 Lopunny
476 LopunnyMega Lopunny
477 Mismagius
478 Honchkrow
479 Glameow
480 Purugly
481 Chingling
482 Stunky
483 Skuntank
484 Bronzor
485 Bronzong
486 Bonsly
487 Mime Jr.
488 Happiny
489 Chatot
490 Spiritomb
491 Gible
492 Gabite
493 Garchomp
494 GarchompMega Garchomp
495 Munchlax
496 Riolu
497 Lucario
498 LucarioMega Lucario
499 Hippopotas
500 Hippowdon
501 Skorupi
502 Drapion
503 Croagunk
504 Toxicroak
505 Carnivine
506 Finneon
507 Lumineon
508 Mantyke
509 Snover
510 Abomasnow
511 AbomasnowMega Abomasnow
512 Weavile
513 Magnezone
514 Lickilicky
515 Rhyperior
516 Tangrowth
517 Electivire
518 Magmortar
519 Togekiss
520 Yanmega
521 Leafeon
522 Glaceon
523 Gliscor
524 Mamoswine
525 Porygon-Z
526 Gallade
527 GalladeMega Gallade
528 Probopass
529 Dusknoir
530 Froslass
531 Rotom
532 RotomHeat Rotom
533 RotomWash Rotom
534 RotomFrost Rotom
535 RotomFan Rotom
536 RotomMow Rotom
537 Uxie
538 Mesprit
539 Azelf
540 Dialga
541 Palkia
542 Heatran
543 Regigigas
544 GiratinaAltered Forme
545 GiratinaOrigin Forme
546 Cresselia
547 Phione
548 Manaphy
549 Darkrai
550 ShayminLand Forme
551 ShayminSky Forme
552 Arceus
553 Victini
554 Snivy
555 Servine
556 Serperior
557 Tepig
558 Pignite
559 Emboar
560 Oshawott
561 Dewott
562 Samurott
563 Patrat
564 Watchog
565 Lillipup
566 Herdier
567 Stoutland
568 Purrloin
569 Liepard
570 Pansage
571 Simisage
572 Pansear
573 Simisear
574 Panpour
575 Simipour
576 Munna
577 Musharna
578 Pidove
579 Tranquill
580 Unfezant
581 Blitzle
582 Zebstrika
583 Roggenrola
584 Boldore
585 Gigalith
586 Woobat
587 Swoobat
588 Drilbur
589 Excadrill
590 Audino
591 AudinoMega Audino
592 Timburr
593 Gurdurr
594 Conkeldurr
595 Tympole
596 Palpitoad
597 Seismitoad
598 Throh
599 Sawk
600 Sewaddle
601 Swadloon
602 Leavanny
603 Venipede
604 Whirlipede
605 Scolipede
606 Cottonee
607 Whimsicott
608 Petilil
609 Lilligant
610 Basculin
611 Sandile
612 Krokorok
613 Krookodile
614 Darumaka
615 DarmanitanStandard Mode
616 DarmanitanZen Mode
617 Maractus
618 Dwebble
619 Crustle
620 Scraggy
621 Scrafty
622 Sigilyph
623 Yamask
624 Cofagrigus
625 Tirtouga
626 Carracosta
627 Archen
628 Archeops
629 Trubbish
630 Garbodor
631 Zorua
632 Zoroark
633 Minccino
634 Cinccino
635 Gothita
636 Gothorita
637 Gothitelle
638 Solosis
639 Duosion
640 Reuniclus
641 Ducklett
642 Swanna
643 Vanillite
644 Vanillish
645 Vanilluxe
646 Deerling
647 Sawsbuck
648 Emolga
649 Karrablast
650 Escavalier
651 Foongus
652 Amoonguss
653 Frillish
654 Jellicent
655 Alomomola
656 Joltik
657 Galvantula
658 Ferroseed
659 Ferrothorn
660 Klink
661 Klang
662 Klinklang
663 Tynamo
664 Eelektrik
665 Eelektross
666 Elgyem
667 Beheeyem
668 Litwick
669 Lampent
670 Chandelure
671 Axew
672 Fraxure
673 Haxorus
674 Cubchoo
675 Beartic
676 Cryogonal
677 Shelmet
678 Accelgor
679 Stunfisk
680 Mienfoo
681 Mienshao
682 Druddigon
683 Golett
684 Golurk
685 Pawniard
686 Bisharp
687 Bouffalant
688 Rufflet
689 Braviary
690 Vullaby
691 Mandibuzz
692 Heatmor
693 Durant
694 Deino
695 Zweilous
696 Hydreigon
697 Larvesta
698 Volcarona
699 Cobalion
700 Terrakion
701 Virizion
702 TornadusIncarnate Forme
703 TornadusTherian Forme
704 ThundurusIncarnate Forme
705 ThundurusTherian Forme
706 Reshiram
707 Zekrom
708 LandorusIncarnate Forme
709 LandorusTherian Forme
710 Kyurem
711 KyuremBlack Kyurem
712 KyuremWhite Kyurem
713 KeldeoOrdinary Forme
714 KeldeoResolute Forme
715 MeloettaAria Forme
716 MeloettaPirouette Forme
717 Genesect
718 Chespin
719 Quilladin
720 Chesnaught
721 Fennekin
722 Braixen
723 Delphox
724 Froakie
725 Frogadier
726 Greninja
727 Bunnelby
728 Diggersby
729 Fletchling
730 Fletchinder
731 Talonflame
732 Scatterbug
733 Spewpa
734 Vivillon
735 Litleo
736 Pyroar
737 Flabébé
738 Floette
739 Florges
740 Skiddo
741 Gogoat
742 Pancham
743 Pangoro
744 Furfrou
745 Espurr
746 MeowsticMale
747 MeowsticFemale
748 Honedge
749 Doublade
750 AegislashBlade Forme
751 AegislashShield Forme
752 Spritzee
753 Aromatisse
754 Swirlix
755 Slurpuff
756 Inkay
757 Malamar
758 Binacle
759 Barbaracle
760 Skrelp
761 Dragalge
762 Clauncher
763 Clawitzer
764 Helioptile
765 Heliolisk
766 Tyrunt
767 Tyrantrum
768 Amaura
769 Aurorus
770 Sylveon
771 Hawlucha
772 Dedenne
773 Carbink
774 Goomy
775 Sliggoo
776 Goodra
777 Klefki
778 Phantump
779 Trevenant
780 PumpkabooAverage Size
781 PumpkabooSmall Size
782 PumpkabooLarge Size
783 PumpkabooSuper Size
784 GourgeistAverage Size
785 GourgeistSmall Size
786 GourgeistLarge Size
787 GourgeistSuper Size
788 Bergmite
789 Avalugg
790 Noibat
791 Noivern
792 Xerneas
793 Yveltal
794 Zygarde50% Forme
795 Diancie
796 DiancieMega Diancie
797 HoopaHoopa Confined
798 HoopaHoopa Unbound
799 Volcanion

In [29]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [32]:
#sorting
#df.sort_values('Name')
df.sort_values('Name', ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [37]:
#sorting multiple([])
df.sort_values(['Type 1','HP'], ascending=[1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

In [41]:
#making new columns
df['Total']=df['HP']+df['Attack']+df['Defense']+df['Sp. Atk']+df['Sp. Def']+df['Speed']
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [42]:
#drop columns
df.drop(columns=['Total'])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [50]:
#adding new column
df['Total'] = df.iloc[:, 4:10].sum(axis=1)
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [58]:
#shifting the new column([])
cols=list(df.columns.values)
df=df[cols[0:4]+[cols[-1]]+cols[4:12]]
df.head()

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,1,False,525,80,82,83,100,100,80
3,3,VenusaurMega Venusaur,Grass,Poison,1,False,625,80,100,123,122,120,80
4,4,Charmander,Fire,NaN,1,False,309,39,52,43,60,50,65

In [59]:
#saving the csv
df.to_csv('modified.csv',index=False)

In [61]:
#filtering data
df.loc[df['Type 1']=='Grass']

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,1,False,525,80,82,83,100,100,80
3,3,VenusaurMega Venusaur,Grass,Poison,1,False,625,80,100,123,122,120,80
48,43,Oddish,Grass,Poison,1,False,320,45,50,55,75,65,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,6,False,313,56,61,65,48,45,38
719,651,Quilladin,Grass,NaN,6,False,405,61,78,95,56,58,57
720,652,Chesnaught,Grass,Fighting,6,False,530,88,107,122,74,75,64
740,672,Skiddo,Grass,NaN,6,False,350,66,65,48,62,57,52
741,673,Gogoat,Grass,NaN,6,False,531,123,100,62,97,81,68

In [62]:
df.loc[(df['Type 1']=='Grass') & (df['Type 2']=='Poison')]

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,1,False,525,80,82,83,100,100,80
3,3,VenusaurMega Venusaur,Grass,Poison,1,False,625,80,100,123,122,120,80
48,43,Oddish,Grass,Poison,1,False,320,45,50,55,75,65,30
49,44,Gloom,Grass,Poison,1,False,395,60,65,70,85,75,40
50,45,Vileplume,Grass,Poison,1,False,490,75,80,85,110,90,50
75,69,Bellsprout,Grass,Poison,1,False,300,50,75,35,70,30,40
76,70,Weepinbell,Grass,Poison,1,False,390,65,90,50,85,45,55
77,71,Victreebel,Grass,Poison,1,False,490,80,105,65,100,70,70
344,315,Roselia,Grass,Poison,3,False,400,50,60,45,100,80,65
451,406,Budew,Grass,Poison,4,False,280,40,30,35,50,70,55
452,407,Roserade,Grass,Poison,4,False,515,60,70,65,125,105,90
651,590,Foongus,Grass,Poison,5,False,294,69,55,45,55,55,15
652,591,Amoonguss,Grass,Poison,5,False,464,114,85,70,85,80,30

In [63]:
df.loc[(df['Type 1']=='Grass') | (df['Type 2']=='Poison')]

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,1,False,525,80,82,83,100,100,80
3,3,VenusaurMega Venusaur,Grass,Poison,1,False,625,80,100,123,122,120,80
16,13,Weedle,Bug,Poison,1,False,195,40,35,30,20,20,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,6,False,313,56,61,65,48,45,38
719,651,Quilladin,Grass,NaN,6,False,405,61,78,95,56,58,57
720,652,Chesnaught,Grass,Fighting,6,False,530,88,107,122,74,75,64
740,672,Skiddo,Grass,NaN,6,False,350,66,65,48,62,57,52
741,673,Gogoat,Grass,NaN,6,False,531,123,100,62,97,81,68

In [82]:
new_df=df.loc[(df['Type 1']=='Grass') | (df['Type 2']=='Poison')]

In [84]:
#Reset Index
new_df= new_df.reset_index()
new_df

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,1,False,525,80,82,83,100,100,80
3,3,VenusaurMega Venusaur,Grass,Poison,1,False,625,80,100,123,122,120,80
16,13,Weedle,Bug,Poison,1,False,195,40,35,30,20,20,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,6,False,313,56,61,65,48,45,38
719,651,Quilladin,Grass,NaN,6,False,405,61,78,95,56,58,57
720,652,Chesnaught,Grass,Fighting,6,False,530,88,107,122,74,75,64
740,672,Skiddo,Grass,NaN,6,False,350,66,65,48,62,57,52
741,673,Gogoat,Grass,NaN,6,False,531,123,100,62,97,81,68

In [85]:
new_df.reset_index(inplace=True)

In [86]:
new_df

,index,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,0,1,Bulbasaur,Grass,Poison,1,False,318,45,49,49,65,65,45
1,1,2,Ivysaur,Grass,Poison,1,False,405,60,62,63,80,80,60
2,2,3,Venusaur,Grass,Poison,1,False,525,80,82,83,100,100,80
3,3,3,VenusaurMega Venusaur,Grass,Poison,1,False,625,80,100,123,122,120,80
4,16,13,Weedle,Bug,Poison,1,False,195,40,35,30,20,20,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,718,650,Chespin,Grass,NaN,6,False,313,56,61,65,48,45,38
85,719,651,Quilladin,Grass,NaN,6,False,405,61,78,95,56,58,57
86,720,652,Chesnaught,Grass,Fighting,6,False,530,88,107,122,74,75,64
87,740,672,Skiddo,Grass,NaN,6,False,350,66,65,48,62,57,52
88,741,673,Gogoat,Grass,NaN,6,False,531,123,100,62,97,81,68

In [87]:
df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
3,3,VenusaurMega Venusaur,Grass,Poison,1,False,625,80,100,123,122,120,80
7,6,CharizardMega Charizard X,Fire,Dragon,1,False,634,78,130,111,130,85,100
8,6,CharizardMega Charizard Y,Fire,Flying,1,False,634,78,104,78,159,115,100
12,9,BlastoiseMega Blastoise,Water,NaN,1,False,630,79,103,120,135,115,78
19,15,BeedrillMega Beedrill,Bug,Poison,1,False,495,65,150,40,15,80,145
23,18,PidgeotMega Pidgeot,Normal,Flying,1,False,579,83,80,80,135,80,121
71,65,AlakazamMega Alakazam,Psychic,NaN,1,False,590,55,50,65,175,95,150
87,80,SlowbroMega Slowbro,Water,Psychic,1,False,590,95,75,180,130,80,30
102,94,GengarMega Gengar,Ghost,Poison,1,False,600,60,65,80,170,95,130
124,115,KangaskhanMega Kangaskhan,Normal,NaN,1,False,590,105,125,100,60,100,100
137,127,PinsirMega Pinsir,Bug,Flying,1,False,600,65,155,120,65,90,105
141,130,GyaradosMega Gyarados,Water,Dark,1,False,640,95,155,109,70,130,81
154,142,AerodactylMega Aerodactyl,Rock,Flying,1,False,615,80,135,85,70,95,150
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,1,True,780,106,190,100,154,100,130
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,1,True,780,106,150,70,194,120,140
168,154,Meganium,Grass,NaN,2,False,525,80,82,100,83,100,80
196,181,AmpharosMega Ampharos,Electric,Dragon,2,False,610,90,95,105,165,110,45
224,208,SteelixMega Steelix,Steel,Ground,2,False,610,75,125,230,55,95,30
229,212,ScizorMega Scizor,Bug,Steel,2,False,600,70,150,140,65,100,75
232,214,HeracrossMega Heracross,Bug,Fighting,2,False,600,80,185,115,40,105,75
248,229,HoundoomMega Houndoom,Dark,Fire,2,False,600,75,90,90,140,90,115
268,248,TyranitarMega Tyranitar,Rock,Dark,2,False,700,100,164,150,95,120,71
275,254,SceptileMega Sceptile,Grass,Dragon,3,False,630,70,110,75,145,85,145
279,257,BlazikenMega Blaziken,Fire,Fighting,3,False,630,80,160,80,130,80,100
283,260,SwampertMega Swampert,Water,Ground,3,False,635,100,150,110,95,110,70
306,282,GardevoirMega Gardevoir,Psychic,Fairy,3,False,618,68,85,65,165,135,100
327,302,SableyeMega Sableye,Dark,Ghost,3,False,480,50,85,125,85,115,20
329,303,MawileMega Mawile,Steel,Fairy,3,False,480,50,105,125,55,95,50
333,306,AggronMega Aggron,Steel,NaN,3,False,630,70,140,230,60,80,50
336,308,MedichamMega Medicham,Fighting,Psychic,3,False,510,60,100,85,80,85,100
339,310,ManectricMega Manectric,Electric,NaN,3,False,575,70,75,80,135,80,135
349,319,SharpedoMega Sharpedo,Water,Dark,3,False,560,70,140,70,110,65,105
354,323,CameruptMega Camerupt,Fire,Ground,3,False,560,70,120,100,145,105,20
366,334,AltariaMega Altaria,Dragon,Fairy,3,False,590,75,110,110,110,105,80
387,354,BanetteMega Banette,Ghost,NaN,3,False,555,64,165,75,93,83,75
393,359,AbsolMega Absol,Dark,NaN,3,False,565,65,150,60,115,60,115
397,362,GlalieMega Glalie,Ice,NaN,3,False,580,80,120,80,120,80,100
409,373,SalamenceMega Salamence,Dragon,Flying,3,False,700,95,145,130,120,90,120
413,376,MetagrossMega Metagross,Steel,Psychic,3,False,700,80,145,150,105,110,110
418,380,LatiasMega Latias,Dragon,Psychic,3,True,700,80,100,120,140,150,110
420,381,LatiosMega Latios,Dragon,Psychic,3,True,700,80,130,100,160,120,110
426,384,RayquazaMega Rayquaza,Dragon,Flying,3,True,780,105,180,100,180,100,115
476,428,LopunnyMega Lopunny,Normal,Fighting,4,False,580,65,136,94,54,96,135
494,445,GarchompMega Garchomp,Dragon,Ground,4,False,700,108,170,115,120,95,92
498,448,LucarioMega Lucario,Fighting,Steel,4,False,625,70,145,88,140,70,112
511,460,AbomasnowMega Abomasnow,Grass,Ice,4,False,594,90,132,105,132,105,30
527,475,GalladeMega Gallade,Psychic,Fighting,4,False,618,68,165,95,65,115,110
591,531,AudinoMega Audino,Normal,Fairy,5,False,545,103,60,126,80,126,50
796,719,DiancieMega Diancie,Rock,Fairy,6,True,700,50,160,110,160,110,110

In [89]:
#dropping(~)
df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,1,False,525,80,82,83,100,100,80
4,4,Charmander,Fire,NaN,1,False,309,39,52,43,60,50,65
5,5,Charmeleon,Fire,NaN,1,False,405,58,64,58,80,65,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,6,True,600,108,100,121,81,95,95
795,719,Diancie,Rock,Fairy,6,True,600,50,100,150,100,150,50
797,720,HoopaHoopa Confined,Psychic,Ghost,6,True,600,80,110,60,150,130,70
798,720,HoopaHoopa Unbound,Psychic,Dark,6,True,680,80,160,60,170,130,80
799,721,Volcanion,Fire,Water,6,True,600,80,110,120,130,90,70

In [92]:
import re

df.loc[df['Type 1'].str.contains('Fire|Grass',flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,1,False,525,80,82,83,100,100,80
3,3,VenusaurMega Venusaur,Grass,Poison,1,False,625,80,100,123,122,120,80
4,4,Charmander,Fire,NaN,1,False,309,39,52,43,60,50,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,6,False,369,62,50,58,73,54,72
736,668,Pyroar,Fire,Normal,6,False,507,86,68,72,109,66,106
740,672,Skiddo,Grass,NaN,6,False,350,66,65,48,62,57,52
741,673,Gogoat,Grass,NaN,6,False,531,123,100,62,97,81,68
799,721,Volcanion,Fire,Water,6,True,600,80,110,120,130,90,70

In [93]:
#filter using regex
df.loc[df['Name'].str.contains('pi[a-z]*',flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
13,10,Caterpie,Bug,NaN,1,False,195,45,30,35,20,20,45
20,16,Pidgey,Normal,Flying,1,False,251,40,45,40,35,35,56
21,17,Pidgeotto,Normal,Flying,1,False,349,63,60,55,50,50,71
22,18,Pidgeot,Normal,Flying,1,False,479,83,80,75,70,70,101
23,18,PidgeotMega Pidgeot,Normal,Flying,1,False,579,83,80,80,135,80,121
30,25,Pikachu,Electric,NaN,1,False,320,35,55,40,50,50,90
42,37,Vulpix,Fire,NaN,1,False,299,38,41,40,50,65,65
76,70,Weepinbell,Grass,Poison,1,False,390,65,90,50,85,45,55
84,78,Rapidash,Fire,NaN,1,False,500,65,100,70,80,80,105
136,127,Pinsir,Bug,NaN,1,False,500,65,125,100,55,70,85
137,127,PinsirMega Pinsir,Bug,Flying,1,False,600,65,155,120,65,90,105
181,167,Spinarak,Bug,Poison,2,False,250,40,60,40,40,40,30
186,172,Pichu,Electric,NaN,2,False,205,20,40,15,35,35,60
189,175,Togepi,Fairy,NaN,2,False,245,35,20,65,40,65,20
202,187,Hoppip,Grass,Flying,2,False,250,35,35,40,35,55,50
219,204,Pineco,Bug,NaN,2,False,290,50,65,90,35,35,15
239,221,Piloswine,Ice,Ground,2,False,450,100,100,80,60,60,50
266,247,Pupitar,Rock,Ground,2,False,410,70,84,70,65,70,51
345,316,Gulpin,Poison,NaN,3,False,302,70,43,53,43,53,40
357,326,Grumpig,Psychic,NaN,3,False,470,80,45,65,90,110,80
358,327,Spinda,Normal,NaN,3,False,360,60,60,60,60,60,60
359,328,Trapinch,Ground,NaN,3,False,290,45,100,45,45,45,10
390,357,Tropius,Grass,Flying,3,False,460,99,68,83,72,87,51
438,393,Piplup,Water,NaN,4,False,314,53,51,53,61,56,40
463,416,Vespiquen,Bug,Flying,4,False,474,70,80,102,80,102,40
488,440,Happiny,Normal,NaN,4,False,220,100,5,5,15,65,30
490,442,Spiritomb,Ghost,Dark,4,False,485,50,92,108,92,108,35
501,451,Skorupi,Poison,Bug,4,False,330,40,50,90,30,55,65
502,452,Drapion,Poison,Dark,4,False,500,70,90,110,60,75,95
557,498,Tepig,Fire,NaN,5,False,308,65,63,45,45,45,45
558,499,Pignite,Fire,Fighting,5,False,418,90,93,55,70,55,55
578,519,Pidove,Normal,Flying,5,False,264,50,55,50,36,30,43
596,536,Palpitoad,Water,Ground,5,False,384,75,65,55,65,55,69
716,648,MeloettaPirouette Forme,Normal,Fighting,5,False,600,100,128,90,77,77,128
718,650,Chespin,Grass,NaN,6,False,313,56,61,65,48,45,38

In [94]:
df.loc[df['Name'].str.contains('^pi[a-z]*',flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
20,16,Pidgey,Normal,Flying,1,False,251,40,45,40,35,35,56
21,17,Pidgeotto,Normal,Flying,1,False,349,63,60,55,50,50,71
22,18,Pidgeot,Normal,Flying,1,False,479,83,80,75,70,70,101
23,18,PidgeotMega Pidgeot,Normal,Flying,1,False,579,83,80,80,135,80,121
30,25,Pikachu,Electric,NaN,1,False,320,35,55,40,50,50,90
136,127,Pinsir,Bug,NaN,1,False,500,65,125,100,55,70,85
137,127,PinsirMega Pinsir,Bug,Flying,1,False,600,65,155,120,65,90,105
186,172,Pichu,Electric,NaN,2,False,205,20,40,15,35,35,60
219,204,Pineco,Bug,NaN,2,False,290,50,65,90,35,35,15
239,221,Piloswine,Ice,Ground,2,False,450,100,100,80,60,60,50
438,393,Piplup,Water,NaN,4,False,314,53,51,53,61,56,40
558,499,Pignite,Fire,Fighting,5,False,418,90,93,55,70,55,55
578,519,Pidove,Normal,Flying,5,False,264,50,55,50,36,30,43

In [96]:
#conditional Changes
df.loc[df['Type 1']=='Fire', 'Type 1']='Flamer'
df

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,1,False,525,80,82,83,100,100,80
3,3,VenusaurMega Venusaur,Grass,Poison,1,False,625,80,100,123,122,120,80
4,4,Charmander,Flamer,NaN,1,False,309,39,52,43,60,50,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,6,True,600,50,100,150,100,150,50
796,719,DiancieMega Diancie,Rock,Fairy,6,True,700,50,160,110,160,110,110
797,720,HoopaHoopa Confined,Psychic,Ghost,6,True,600,80,110,60,150,130,70
798,720,HoopaHoopa Unbound,Psychic,Dark,6,True,680,80,160,60,170,130,80
799,721,Volcanion,Flamer,Water,6,True,600,80,110,120,130,90,70

In [99]:
df.loc[df['Type 1']=='Flamer', 'Legendary']=True
df

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,1,False,525,80,82,83,100,100,80
3,3,VenusaurMega Venusaur,Grass,Poison,1,False,625,80,100,123,122,120,80
4,4,Charmander,Flamer,NaN,1,True,309,39,52,43,60,50,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,6,True,600,50,100,150,100,150,50
796,719,DiancieMega Diancie,Rock,Fairy,6,True,700,50,160,110,160,110,110
797,720,HoopaHoopa Confined,Psychic,Ghost,6,True,600,80,110,60,150,130,70
798,720,HoopaHoopa Unbound,Psychic,Dark,6,True,680,80,160,60,170,130,80
799,721,Volcanion,Flamer,Water,6,True,600,80,110,120,130,90,70

In [101]:
df=pd.read_csv('/content/modified.csv')
df

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,1,False,525,80,82,83,100,100,80
3,3,VenusaurMega Venusaur,Grass,Poison,1,False,625,80,100,123,122,120,80
4,4,Charmander,Fire,NaN,1,False,309,39,52,43,60,50,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,6,True,600,50,100,150,100,150,50
796,719,DiancieMega Diancie,Rock,Fairy,6,True,700,50,160,110,160,110,110
797,720,HoopaHoopa Confined,Psychic,Ghost,6,True,600,80,110,60,150,130,70
798,720,HoopaHoopa Unbound,Psychic,Dark,6,True,680,80,160,60,170,130,80
799,721,Volcanion,Fire,Water,6,True,600,80,110,120,130,90,70

In [104]:
df.loc[df['Total']>500, ['Generation', 'Legendary']]= ['Test1', 'Test 2']
df

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,Test1,Test 2,525,80,82,83,100,100,80
3,3,VenusaurMega Venusaur,Grass,Poison,Test1,Test 2,625,80,100,123,122,120,80
4,4,Charmander,Fire,NaN,1,False,309,39,52,43,60,50,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,Test1,Test 2,600,50,100,150,100,150,50
796,719,DiancieMega Diancie,Rock,Fairy,Test1,Test 2,700,50,160,110,160,110,110
797,720,HoopaHoopa Confined,Psychic,Ghost,Test1,Test 2,600,80,110,60,150,130,70
798,720,HoopaHoopa Unbound,Psychic,Dark,Test1,Test 2,680,80,160,60,170,130,80
799,721,Volcanion,Fire,Water,Test1,Test 2,600,80,110,120,130,90,70

In [105]:
df=pd.read_csv('/content/modified.csv')
df

,#,Name,Type 1,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
0,1,Bulbasaur,Grass,Poison,1,False,318,45,49,49,65,65,45
1,2,Ivysaur,Grass,Poison,1,False,405,60,62,63,80,80,60
2,3,Venusaur,Grass,Poison,1,False,525,80,82,83,100,100,80
3,3,VenusaurMega Venusaur,Grass,Poison,1,False,625,80,100,123,122,120,80
4,4,Charmander,Fire,NaN,1,False,309,39,52,43,60,50,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,6,True,600,50,100,150,100,150,50
796,719,DiancieMega Diancie,Rock,Fairy,6,True,700,50,160,110,160,110,110
797,720,HoopaHoopa Confined,Psychic,Ghost,6,True,600,80,110,60,150,130,70
798,720,HoopaHoopa Unbound,Psychic,Dark,6,True,680,80,160,60,170,130,80
799,721,Volcanion,Fire,Water,6,True,600,80,110,120,130,90,70

In [108]:
#aggregate Statistics
df.groupby(['Type 1']).mean().sort_values('Defense', ascending=False)

,#,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
Type 1,,,,,,,,,,
Steel,442.851852,3.851852,0.148148,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259
Rock,392.727273,3.454545,0.090909,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091
Dragon,474.375000,3.875000,0.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250
Ground,356.281250,3.156250,0.125000,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250
Ghost,486.500000,4.187500,0.062500,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750
Water,303.089286,2.857143,0.035714,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286
Ice,423.541667,3.541667,0.083333,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333
Grass,344.871429,3.357143,0.042857,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571
Bug,334.492754,3.217391,0.000000,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159
Dark,461.354839,4.032258,0.064516,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290
Poison,251.785714,2.535714,0.000000,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429
Fire,327.403846,3.211538,0.096154,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308
Psychic,380.807018,3.385965,0.245614,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228
Electric,363.500000,3.272727,0.090909,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000
Flying,677.750000,5.500000,0.500000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000
Fighting,363.851852,3.370370,0.000000,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074
Fairy,449.529412,4.117647,0.058824,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235
Normal,319.173469,3.051020,0.020408,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020

In [109]:
#aggregate Statistics
df.groupby(['Type 1']).mean().sort_values('Attack', ascending=False)

,#,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
Type 1,,,,,,,,,,
Dragon,474.375000,3.875000,0.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250
Fighting,363.851852,3.370370,0.000000,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074
Ground,356.281250,3.156250,0.125000,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250
Rock,392.727273,3.454545,0.090909,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091
Steel,442.851852,3.851852,0.148148,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259
Dark,461.354839,4.032258,0.064516,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290
Fire,327.403846,3.211538,0.096154,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308
Flying,677.750000,5.500000,0.500000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000
Poison,251.785714,2.535714,0.000000,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429
Water,303.089286,2.857143,0.035714,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286
Ghost,486.500000,4.187500,0.062500,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750
Normal,319.173469,3.051020,0.020408,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020
Grass,344.871429,3.357143,0.042857,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571
Ice,423.541667,3.541667,0.083333,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333
Psychic,380.807018,3.385965,0.245614,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228
Bug,334.492754,3.217391,0.000000,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159
Electric,363.500000,3.272727,0.090909,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000
Fairy,449.529412,4.117647,0.058824,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235

In [110]:
#doesn't make sense still for function
df.groupby(['Type 1']).sum()

,#,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
Type 1,,,,,,,,,,
Bug,23080,222,0,26146,3925,4897,4880,3717,4471,4256
Dark,14302,125,2,13818,2071,2740,2177,2314,2155,2361
Dragon,15180,124,12,17617,2666,3588,2764,3099,2843,2657
Electric,15994,144,4,19510,2631,3040,2917,3961,3243,3718
Fairy,7642,70,1,7024,1260,1046,1117,1335,1440,826
Fighting,9824,91,0,11244,1886,2613,1780,1434,1747,1784
Fire,17025,167,5,23820,3635,4408,3524,4627,3755,3871
Flying,2711,22,2,1940,283,315,265,377,290,410
Ghost,15568,134,2,14066,2062,2361,2598,2539,2447,2059
Grass,24141,235,3,29480,4709,5125,4956,5425,4930,4335
Ground,11401,101,4,14000,2361,3064,2715,1807,2008,2045
Ice,10165,85,2,10403,1728,1746,1714,1861,1831,1523
Normal,31279,299,2,39365,7573,7200,5865,5470,6245,7012
Poison,7050,71,0,11176,1883,2091,1927,1692,1803,1780
Psychic,21706,193,14,27129,4026,4073,3858,5609,4918,4645
Rock,17280,152,4,19965,2876,4086,4435,2787,3321,2460
Steel,11957,104,4,13168,1761,2503,3412,1823,2177,1492
Water,33946,320,4,48211,8071,8305,8170,8379,7898,7388

In [111]:
df.groupby(['Type 1']).count()

,#,Name,Type 2,Generation,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
Type 1,,,,,,,,,,,,
Bug,69,69,52,69,69,69,69,69,69,69,69,69
Dark,31,31,21,31,31,31,31,31,31,31,31,31
Dragon,32,32,21,32,32,32,32,32,32,32,32,32
Electric,44,44,17,44,44,44,44,44,44,44,44,44
Fairy,17,17,2,17,17,17,17,17,17,17,17,17
Fighting,27,27,7,27,27,27,27,27,27,27,27,27
Fire,52,52,24,52,52,52,52,52,52,52,52,52
Flying,4,4,2,4,4,4,4,4,4,4,4,4
Ghost,32,32,22,32,32,32,32,32,32,32,32,32
Grass,70,70,37,70,70,70,70,70,70,70,70,70
Ground,32,32,19,32,32,32,32,32,32,32,32,32
Ice,24,24,11,24,24,24,24,24,24,24,24,24
Normal,98,98,37,98,98,98,98,98,98,98,98,98
Poison,28,28,13,28,28,28,28,28,28,28,28,28
Psychic,57,57,19,57,57,57,57,57,57,57,57,57
Rock,44,44,35,44,44,44,44,44,44,44,44,44
Steel,27,27,22,27,27,27,27,27,27,27,27,27
Water,112,112,53,112,112,112,112,112,112,112,112,112

In [114]:
df['Count']=1
df.groupby(['Type 1','Type 2']).count()['Count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: Count, Length: 136, dtype: int64

In [118]:
#working with large data

for df in pd.read_csv('/content/modified.csv',chunksize=5):
    print(df)

   #                   Name Type 1  Type 2  Generation  Legendary  Total  HP  \
0  1              Bulbasaur  Grass  Poison           1      False    318  45
1  2                Ivysaur  Grass  Poison           1      False    405  60
2  3               Venusaur  Grass  Poison           1      False    525  80
3  3  VenusaurMega Venusaur  Grass  Poison           1      False    625  80
4  4             Charmander   Fire     NaN           1      False    309  39

   Attack  Defense  Sp. Atk  Sp. Def  Speed
0      49       49       65       65     45
1      62       63       80       80     60
2      82       83      100      100     80
3     100      123      122      120     80
4      52       43       60       50     65
   #                       Name Type 1  Type 2  Generation  Legendary  Total  \
5  5                 Charmeleon   Fire     NaN           1      False    405
6  6                  Charizard   Fire  Flying           1      False    534
7  6  CharizardMega Charizard X   Fire  Dragon           1      False    634
8  6  CharizardMega Charizard Y   Fire  Flying           1      False    634
9  7                   Squirtle  Water     NaN           1      False    314

   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
5  58      64       58       80       65     80
6  78      84       78      109       85    100
7  78     130      111      130       85    100
8  78     104       78      159      115    100
9  44      48       65       50       64     43
     #                     Name Type 1  Type 2  Generation  Legendary  Total  \
10   8                Wartortle  Water     NaN           1      False    405
11   9                Blastoise  Water     NaN           1      False    530
12   9  BlastoiseMega Blastoise  Water     NaN           1      False    630
13  10                 Caterpie    Bug     NaN           1      False    195
14  11                  Metapod    Bug     NaN           1      False    205

    HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
10  59      63       80       65       80     58
11  79      83      100       85      105     78
12  79     103      120      135      115     78
13  45      30       35       20       20     45
14  50      20       55       25       25     30
     #                   Name Type 1  Type 2  Generation  Legendary  Total  \
15  12             Butterfree    Bug  Flying           1      False    395
16  13                 Weedle    Bug  Poison           1      False    195
17  14                 Kakuna    Bug  Poison           1      False    205
18  15               Beedrill    Bug  Poison           1      False    395
19  15  BeedrillMega Beedrill    Bug  Poison           1      False    495

    HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
15  60      45       50       90       80     70
16  40      35       30       20       20     50
17  45      25       50       25       25     35
18  65      90       40       45       80     75
19  65     150       40       15       80    145
     #                 Name  Type 1  Type 2  Generation  Legendary  Total  HP  \
20  16               Pidgey  Normal  Flying           1      False    251  40
21  17            Pidgeotto  Normal  Flying           1      False    349  63
22  18              Pidgeot  Normal  Flying           1      False    479  83
23  18  PidgeotMega Pidgeot  Normal  Flying           1      False    579  83
24  19              Rattata  Normal     NaN           1      False    253  30

    Attack  Defense  Sp. Atk  Sp. Def  Speed
20      45       40       35       35     56
21      60       55       50       50     71
22      80       75       70       70    101
23      80       80      135       80    121
24      56       35       25       35     72
     #      Name  Type 1  Type 2  Generation  Legendary  Total  HP  Attack  \
25  20  Raticate  Normal     NaN           1      False    413  55      81
26  21   Spearow  Normal  Flying           1      False    262  40      60
27  22    Fearow  Normal  Flying           1      False    442  65      90
28  23     Ekans  Poison     NaN           1      False    288  35      60
29  24     Arbok  Poison     NaN           1      False    438  60      85

    Defense  Sp. Atk  Sp. Def  Speed
25       60       50       70     97
26       30       31       31     70
27       65       61       61    100
28       44       40       54     55
29       69       65       79     80
     #              Name    Type 1  Type 2  Generation  Legendary  Total  HP  \
30  25           Pikachu  Electric     NaN           1      False    320  35
31  26            Raichu  Electric     NaN           1      False    485  60
32  27         Sandshrew    Ground     NaN           1      False    300  50
33  28         Sandslash    Ground     NaN           1      False    450  75
34  29  Nidoran (Female)    Poison     NaN           1      False    275  55

    Attack  Defense  Sp. Atk  Sp. Def  Speed
30      55       40       50       50     90
31      90       55       90       80    110
32      75       85       20       30     40
33     100      110       45       55     65
34      47       52       40       40     41
     #            Name  Type 1  Type 2  Generation  Legendary  Total  HP  \
35  30        Nidorina  Poison     NaN           1      False    365  70
36  31       Nidoqueen  Poison  Ground           1      False    505  90
37  32  Nidoran (Male)  Poison     NaN           1      False    273  46
38  33        Nidorino  Poison     NaN           1      False    365  61
39  34        Nidoking  Poison  Ground           1      False    505  81

    Attack  Defense  Sp. Atk  Sp. Def  Speed
35      62       67       55       55     56
36      92       87       75       85     76
37      57       40       40       40     50
38      72       57       55       55     65
39     102       77       85       75     85
     #        Name  Type 1 Type 2  Generation  Legendary  Total   HP  Attack  \
40  35    Clefairy   Fairy    NaN           1      False    323   70      45
41  36    Clefable   Fairy    NaN           1      False    483   95      70
42  37      Vulpix    Fire    NaN           1      False    299   38      41
43  38   Ninetales    Fire    NaN           1      False    505   73      76
44  39  Jigglypuff  Normal  Fairy           1      False    270  115      45

    Defense  Sp. Atk  Sp. Def  Speed
40       48       60       65     35
41       73       95       90     60
42       40       50       65     65
43       75       81      100    100
44       20       45       25     20
     #        Name  Type 1  Type 2  Generation  Legendary  Total   HP  Attack  \
45  40  Wigglytuff  Normal   Fairy           1      False    435  140      70
46  41       Zubat  Poison  Flying           1      False    245   40      45
47  42      Golbat  Poison  Flying           1      False    455   75      80
48  43      Oddish   Grass  Poison           1      False    320   45      50
49  44       Gloom   Grass  Poison           1      False    395   60      65

    Defense  Sp. Atk  Sp. Def  Speed
45       45       85       50     45
46       35       30       40     55
47       70       65       75     90
48       55       75       65     30
49       70       85       75     40
     #       Name Type 1  Type 2  Generation  Legendary  Total  HP  Attack  \
50  45  Vileplume  Grass  Poison           1      False    490  75      80
51  46      Paras    Bug   Grass           1      False    285  35      70
52  47   Parasect    Bug   Grass           1      False    405  60      95
53  48    Venonat    Bug  Poison           1      False    305  60      55
54  49   Venomoth    Bug  Poison           1      False    450  70      65

    Defense  Sp. Atk  Sp. Def  Speed
50       85      110       90     50
51       55       45       55     25
52       80       60       80     30
53       50       40       55     45
54       60       90       75     90
     #     Name  Type 1  Type 2  Generation  Legendary  Total  HP  Attack  \
55  50  Diglett  Ground     NaN           1      False    265  10      55
56  51  Dugtrio  Ground     NaN           1      False    405  35      80
57  52   Meowth  Normal     NaN           1      False    290  40      45
58  53  Persian  Normal     NaN           1      False    440  65      70
59  54  Psyduck   Water     NaN           1      False    320  50      52

    Defense  Sp. Atk  Sp. Def  Speed
55       25       35       45     95
56       50       50       70    120
57       35       40       40     90
58       60       65       65    115
59       48       65       50     55
     #       Name    Type 1  Type 2  Generation  Legendary  Total  HP  Attack  \
60  55    Golduck     Water     NaN           1      False    500  80      82
61  56     Mankey  Fighting     NaN           1      False    305  40      80
62  57   Primeape  Fighting     NaN           1      False    455  65     105
63  58  Growlithe      Fire     NaN           1      False    350  55      70
64  59   Arcanine      Fire     NaN           1      False    555  90     110

    Defense  Sp. Atk  Sp. Def  Speed
60       78       95       80     85
61       35       35       45     70
62       60       60       70     95
63       45       70       50     60
64       80      100       80     95
     #       Name   Type 1    Type 2  Generation  Legendary  Total  HP  \
65  60    Poliwag    Water       NaN           1      False    300  40
66  61  Poliwhirl    Water       NaN           1      False    385  65
67  62  Poliwrath    Water  Fighting           1      False    510  90
68  63       Abra  Psychic       NaN           1      False    310  25
69  64    Kadabra  Psychic       NaN           1      False    400  40

    Attack  Defense  Sp. Atk  Sp. Def  Speed
65      50       40       40       40     90
66      65       65       50       50     90
67      95       95       70       90     70
68      20       15      105       55     90
69      35       30      120       70    105
     #                   Name    Type 1  Type 2  Generation  Legendary  Total  \
70  65               Alakazam   Psychic     NaN           1      False    500
71  65  AlakazamMega Alakazam   Psychic     NaN           1      False    590
72  66                 Machop  Fighting     NaN           1      False    305
73  67                Machoke  Fighting     NaN           1      False    405
74  68                Machamp  Fighting     NaN           1      False    505

    HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
70  55      50       45      135       95    120
71  55      50       65      175       95    150
72  70      80       50       35       35     35
73  80     100       70       50       60     45
74  90     130       80       65       85     55
     #        Name Type 1  Type 2  Generation  Legendary  Total  HP  Attack  \
75  69  Bellsprout  Grass  Poison           1      False    300  50      75
76  70  Weepinbell  Grass  Poison           1      False    390  65      90
77  71  Victreebel  Grass  Poison           1      False    490  80     105
78  72   Tentacool  Water  Poison           1      False    335  40      40
79  73  Tentacruel  Water  Poison           1      False    515  80      70

    Defense  Sp. Atk  Sp. Def  Speed
75       35       70       30     40
76       50       85       45     55
77       65      100       70     70
78       35       50      100     70
79       65       80      120    100
     #      Name Type 1  Type 2  Generation  Legendary  Total  HP  Attack  \
80  74   Geodude   Rock  Ground           1      False    300  40      80
81  75  Graveler   Rock  Ground           1      False    390  55      95
82  76     Golem   Rock  Ground           1      False    495  80     120
83  77    Ponyta   Fire     NaN           1      False    410  50      85
84  78  Rapidash   Fire     NaN           1      False    500  65     100

    Defense  Sp. Atk  Sp. Def  Speed
80      100       30       30     20
81      115       45       45     35
82      130       55       65     45
83       55       65       65     90
84       70       80       80    105
     #                 Name    Type 1   Type 2  Generation  Legendary  Total  \
85  79             Slowpoke     Water  Psychic           1      False    315
86  80              Slowbro     Water  Psychic           1      False    490
87  80  SlowbroMega Slowbro     Water  Psychic           1      False    590
88  81            Magnemite  Electric    Steel           1      False    325
89  82             Magneton  Electric    Steel           1      False    465

    HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
85  90      65       65       40       40     15
86  95      75      110      100       80     30
87  95      75      180      130       80     30
88  25      35       70       95       55     45
89  50      60       95      120       70     70
     #        Name  Type 1  Type 2  Generation  Legendary  Total  HP  Attack  \
90  83  Farfetch'd  Normal  Flying           1      False    352  52      65
91  84       Doduo  Normal  Flying           1      False    310  35      85
92  85      Dodrio  Normal  Flying           1      False    460  60     110
93  86        Seel   Water     NaN           1      False    325  65      45
94  87     Dewgong   Water     Ice           1      False    475  90      70

    Defense  Sp. Atk  Sp. Def  Speed
90       55       58       62     60
91       45       35       35     75
92       70       60       60    100
93       55       45       70     45
94       80       70       95     70
     #      Name  Type 1  Type 2  Generation  Legendary  Total   HP  Attack  \
95  88    Grimer  Poison     NaN           1      False    325   80      80
96  89       Muk  Poison     NaN           1      False    500  105     105
97  90  Shellder   Water     NaN           1      False    305   30      65
98  91  Cloyster   Water     Ice           1      False    525   50      95
99  92    Gastly   Ghost  Poison           1      False    310   30      35

    Defense  Sp. Atk  Sp. Def  Speed
95       50       40       50     25
96       75       65      100     50
97      100       45       25     40
98      180       85       45     70
99       30      100       35     80
      #               Name   Type 1  Type 2  Generation  Legendary  Total  HP  \
100  93            Haunter    Ghost  Poison           1      False    405  45
101  94             Gengar    Ghost  Poison           1      False    500  60
102  94  GengarMega Gengar    Ghost  Poison           1      False    600  60
103  95               Onix     Rock  Ground           1      False    385  35
104  96            Drowzee  Psychic     NaN           1      False    328  60

     Attack  Defense  Sp. Atk  Sp. Def  Speed
100      50       45      115       55     95
101      65       60      130       75    110
102      65       80      170       95    130
103      45      160       30       45     70
104      48       45       43       90     42
       #       Name    Type 1  Type 2  Generation  Legendary  Total  HP  \
105   97      Hypno   Psychic     NaN           1      False    483  85
106   98     Krabby     Water     NaN           1      False    325  30
107   99    Kingler     Water     NaN           1      False    475  55
108  100    Voltorb  Electric     NaN           1      False    330  40
109  101  Electrode  Electric     NaN           1      False    480  60

     Attack  Defense  Sp. Atk  Sp. Def  Speed
105      73       70       73      115     67
106     105       90       25       25     50
107     130      115       50       50     75
108      30       50       55       55    100
109      50       70       80       80    140
       #       Name    Type 1   Type 2  Generation  Legendary  Total  HP  \
110  102  Exeggcute     Grass  Psychic           1      False    325  60
111  103  Exeggutor     Grass  Psychic           1      False    520  95
112  104     Cubone    Ground      NaN           1      False    320  50
113  105    Marowak    Ground      NaN           1      False    425  60
114  106  Hitmonlee  Fighting      NaN           1      False    455  50

     Attack  Defense  Sp. Atk  Sp. Def  Speed
110      40       80       60       45     40
111      95       85      125       65     55
112      50       95       40       50     35
113      80      110       50       80     45
114     120       53       35      110     87
       #        Name    Type 1 Type 2  Generation  Legendary  Total  HP  \
115  107  Hitmonchan  Fighting    NaN           1      False    455  50
116  108   Lickitung    Normal    NaN           1      False    385  90
117  109     Koffing    Poison    NaN           1      False    340  40
118  110     Weezing    Poison    NaN           1      False    490  65
119  111     Rhyhorn    Ground   Rock           1      False    345  80

     Attack  Defense  Sp. Atk  Sp. Def  Speed
115     105       79       35      110     76
116      55       75       60       75     30
117      65       95       60       45     35
118      90      120       85       70     60
119      85       95       30       30     25
       #                       Name  Type 1 Type 2  Generation  Legendary  \
120  112                     Rhydon  Ground   Rock           1      False
121  113                    Chansey  Normal    NaN           1      False
122  114                    Tangela   Grass    NaN           1      False
123  115                 Kangaskhan  Normal    NaN           1      False
124  115  KangaskhanMega Kangaskhan  Normal    NaN           1      False

     Total   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
120    485  105     130      120       45       45     40
121    450  250       5        5       35      105     50
122    435   65      55      115      100       40     60
123    490  105      95       80       40       80     90
124    590  105     125      100       60      100    100
       #     Name Type 1  Type 2  Generation  Legendary  Total  HP  Attack  \
125  116   Horsea  Water     NaN           1      False    295  30      40
126  117   Seadra  Water     NaN           1      False    440  55      65
127  118  Goldeen  Water     NaN           1      False    320  45      67
128  119  Seaking  Water     NaN           1      False    450  80      92
129  120   Staryu  Water     NaN           1      False    340  30      45

     Defense  Sp. Atk  Sp. Def  Speed
125       70       70       25     60
126       95       95       45     85
127       60       35       50     63
128       65       65       80     68
129       55       70       55     85
       #        Name    Type 1   Type 2  Generation  Legendary  Total  HP  \
130  121     Starmie     Water  Psychic           1      False    520  60
131  122    Mr. Mime   Psychic    Fairy           1      False    460  40
132  123     Scyther       Bug   Flying           1      False    500  70
133  124        Jynx       Ice  Psychic           1      False    455  65
134  125  Electabuzz  Electric      NaN           1      False    490  65

     Attack  Defense  Sp. Atk  Sp. Def  Speed
130      75       85      100       85    115
131      45       65      100      120     90
132     110       80       55       80    105
133      50       35      115       95     95
134      83       57       95       85    105
       #               Name  Type 1  Type 2  Generation  Legendary  Total  HP  \
135  126             Magmar    Fire     NaN           1      False    495  65
136  127             Pinsir     Bug     NaN           1      False    500  65
137  127  PinsirMega Pinsir     Bug  Flying           1      False    600  65
138  128             Tauros  Normal     NaN           1      False    490  75
139  129           Magikarp   Water     NaN           1      False    200  20

     Attack  Defense  Sp. Atk  Sp. Def  Speed
135      95       57      100       85     93
136     125      100       55       70     85
137     155      120       65       90    105